# Generated by Django 4.2.13 on 2024-07-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_song_year_of_release_song_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
    ]
